# 📊 Regresión Lineal Múltiple: Predicción de Rentabilidad de Startups

## 🎯 Introducción

La **Regresión Lineal Múltiple** es una extensión natural de la regresión lineal simple que permite **predecir una variable continua** usando **múltiples variables predictoras** simultáneamente.

**En este notebook** aprenderás a:
- Trabajar con múltiples variables predictoras
- Dividir datos en conjuntos de entrenamiento y prueba
- Entrenar un modelo de regresión lineal múltiple
- Evaluar el rendimiento con RMSE
- Comparar modelos con diferentes conjuntos de features
- Detectar overfitting comparando errores de train vs test

### 💼 Caso de Uso: Predicción de Rentabilidad de Startups

Usaremos el dataset **50 Startups** que contiene información de 50 empresas emergentes con:
- **R&D Spend**: Gasto en investigación y desarrollo ($)
- **Administration**: Gastos administrativos ($)
- **Marketing Spend**: Gasto en marketing ($)
- **State**: Estado donde opera (categórica) - *la omitiremos en este análisis*
- **Profit** (target): Rentabilidad de la empresa ($)

**Objetivo**: Construir un modelo que **prediga la rentabilidad** de una startup basándose en sus gastos en diferentes áreas.

## 📐 Fundamentos Matemáticos

La regresión lineal múltiple extiende la ecuación de la recta a múltiples dimensiones:

$$y = b_0 + b_1x_1 + b_2x_2 + b_3x_3 + ... + b_nx_n$$

Donde:
- **y**: Variable a predecir (Profit)
- **x₁, x₂, x₃**: Variables predictoras (R&D, Admin, Marketing)
- **b₀**: Intercepto (rentabilidad base)
- **b₁, b₂, b₃**: Coeficientes - contribución de cada variable al profit

El algoritmo encuentra los valores óptimos de todos los coeficientes minimizando el error cuadrático.

## 📑 Contenido del notebook:

### **📥 1. Carga y Exploración de Datos**
- Importar dataset de 50 Startups desde GitHub
- Explorar estructura y variables
- Eliminar variable categórica State

### **🔀 2. Preparación de Datos**
- Separar variables predictoras (X) y objetivo (y)
- División train/test (80/20)
- Importancia del random_state

### **🤖 3. Entrenamiento del Modelo**
- Crear modelo LinearRegression
- Entrenar con datos de entrenamiento
- Hacer predicciones sobre test

### **📊 4. Evaluación del Rendimiento**
- Calcular RMSE (Root Mean Squared Error)
- Interpretar el error del modelo

### **🔍 5. Selección de Features**
- Experimento: Usar solo 2 features
- Comparar rendimiento con modelo completo
- Identificar features más importantes

### **⚠️ 6. Detección de Overfitting**
- Calcular error en train vs test
- Detectar sobreajuste del modelo
- Interpretar resultados

---

## 💡 Regresión Simple vs Múltiple

| Aspecto | Regresión Simple | Regresión Múltiple |
|---------|------------------|-------------------|
| **Variables predictoras** | 1 (univariada) | Múltiples (multivariada) |
| **Ecuación** | y = mx + n | y = b₀ + b₁x₁ + b₂x₂ + ... |
| **Interpretación** | Muy fácil | Requiere análisis de coeficientes |
| **Poder predictivo** | Limitado | Mayor (captura relaciones complejas) |
| **Riesgo de overfitting** | Bajo | Mayor (más parámetros) |

**Ventajas de Regresión Múltiple**:
- ✅ Mayor poder predictivo
- ✅ Captura interacciones entre variables
- ✅ Más realista para problemas reales

**Desafíos**:
- ⚠️ Multicolinealidad (variables correlacionadas)
- ⚠️ Mayor riesgo de overfitting
- ⚠️ Interpretación más compleja

# 📥 1. Carga y Exploración de Datos

Comenzamos cargando el dataset de 50 Startups y realizando una exploración inicial.

In [1]:
# Importar librerías necesarias
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("📥 Cargando dataset de 50 Startups...")

# Cargar dataset desde GitHub
url = "https://raw.githubusercontent.com/gakudo-ai/open-datasets/refs/heads/main/50_Startups.csv"
df = pd.read_csv(url)

print(f"✅ Dataset cargado correctamente")
print(f"\n📊 Dimensiones del dataset: {df.shape[0]} filas, {df.shape[1]} columnas")

# Explorar primeras filas
print("\n🔹 Primeras filas del dataset:")
display(df.head())

print("\n💡 Variables del dataset:")
print("  🔹 R&D Spend: Gasto en I+D ($)")
print("  🔹 Administration: Gastos administrativos ($)")
print("  🔹 Marketing Spend: Gasto en marketing ($)")
print("  🔹 State: Estado de operación (categórica)")
print("  🔹 Profit: Rentabilidad (target) ($)")

📥 Cargando dataset de 50 Startups...
✅ Dataset cargado correctamente

📊 Dimensiones del dataset: 50 filas, 5 columnas

🔹 Primeras filas del dataset:

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

💡 Variables del dataset:
  🔹 R&D Spend: Gasto en I+D ($)
  🔹 Administration: Gastos administrativos ($)
  🔹 Marketing Spend: Gasto en marketing ($)
  🔹 State: Estado de operación (categórica)
  🔹 Profit: Rentabilidad (target) ($)

In [2]:
# Eliminar variable categórica 'State'
# En este ejercicio nos enfocamos solo en variables numéricas
df_num = df.drop('State', axis=1)

print("🔹 Dataset después de eliminar 'State':")
display(df_num.head())

print(f"\n✅ Variables restantes: {list(df_num.columns)}")
print(f"📊 Todas las variables son numéricas: {df_num.shape[1]} columnas")

🔹 Dataset después de eliminar 'State':

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

✅ Variables restantes: ['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']
📊 Todas las variables son numéricas: 4 columnas

# 🔀 2. Preparación de Datos

Separamos las variables predictoras del objetivo y dividimos los datos en conjuntos de entrenamiento y prueba.

## ¿Por qué dividir en Train/Test?

- **Train (80%)**: Datos que el modelo "ve" durante el entrenamiento
- **Test (20%)**: Datos que el modelo NO ve - simula datos futuros
- **Objetivo**: Evaluar cómo generaliza el modelo a datos nuevos

In [3]:
# Separar variables predictoras (X) y objetivo (y)
X = df_num.drop('Profit', axis=1)  # Variables de entrada: R&D, Admin, Marketing
y = df_num['Profit']                # Variable objetivo: Profit

print("🔹 Variables predictoras (X):")
display(X.head())

print(f"\n🔹 Variable objetivo (y): Profit")
print(y.head().values)

# División train/test
x_train, x_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,      # 20% para test
    random_state=42     # Para reproducibilidad
)

print(f"\n📊 División completada:")
print(f"  🔹 Train: {x_train.shape[0]} muestras ({x_train.shape[0]/len(X)*100:.0f}%)")
print(f"  🔹 Test: {x_test.shape[0]} muestras ({x_test.shape[0]/len(X)*100:.0f}%)")
print(f"  🔹 Features: {x_train.shape[1]} variables predictoras")

print(f"\n💡 random_state=42 garantiza que la división sea siempre igual")

🔹 Variables predictoras (X):

   R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

🔹 Variable objetivo (y): Profit
[192261.83 191792.06 191050.39 182901.99 166187.94]

📊 División completada:
  🔹 Train: 40 muestras (80%)
  🔹 Test: 10 muestras (20%)
  🔹 Features: 3 variables predictoras

💡 random_state=42 garantiza que la división sea siempre igual

# 🤖 3. Entrenamiento del Modelo

Entrenamos un modelo de **Regresión Lineal Múltiple** usando scikit-learn.

## ¿Qué hace el modelo?

El modelo busca la ecuación óptima:

$$Profit = b_0 + b_1 \cdot RD + b_2 \cdot Admin + b_3 \cdot Marketing$$

Donde minimiza el error cuadrático entre las predicciones y los valores reales.

In [4]:
# Crear modelo de regresión lineal múltiple
lin_reg = LinearRegression()

# Entrenar el modelo con los datos de train
lin_reg.fit(x_train, y_train)

print("✅ Modelo entrenado exitosamente\n")

# Examinar los coeficientes aprendidos
print("📐 Ecuación del modelo:")
print(f"\n   Profit = {lin_reg.intercept_:.2f}")

for i, col in enumerate(x_train.columns):
    signo = "+" if lin_reg.coef_[i] >= 0 else ""
    print(f"            {signo} {lin_reg.coef_[i]:.2f} × {col}")

print(f"\n💡 Interpretación de coeficientes:")
print(f"  🔹 Intercepto (b₀): {lin_reg.intercept_:.2f}")
print(f"     → Profit base cuando todos los gastos son 0")

for i, col in enumerate(x_train.columns):
    print(f"  🔹 {col}: {lin_reg.coef_[i]:.2f}")
    if lin_reg.coef_[i] > 0:
        print(f"     → Por cada $1 extra en {col}, el profit aumenta ${lin_reg.coef_[i]:.4f}")
    else:
        print(f"     → Por cada $1 extra en {col}, el profit disminuye ${abs(lin_reg.coef_[i]):.4f}")

# Hacer predicciones sobre el conjunto de test
y_predictions = lin_reg.predict(x_test)

print(f"\n🔮 Predicciones realizadas sobre {len(y_predictions)} muestras de test")

✅ Modelo entrenado exitosamente

📐 Ecuación del modelo:

   Profit = 54071.88
            + 0.80 × R&D Spend
             -0.07 × Administration
            + 0.03 × Marketing Spend

💡 Interpretación de coeficientes:
  🔹 Intercepto (b₀): 54071.88
     → Profit base cuando todos los gastos son 0
  🔹 R&D Spend: 0.80
     → Por cada $1 extra en R&D Spend, el profit aumenta $0.8038
  🔹 Administration: -0.07
     → Por cada $1 extra en Administration, el profit disminuye $0.0679
  🔹 Marketing Spend: 0.03
     → Por cada $1 extra en Marketing Spend, el profit aumenta $0.0312

🔮 Predicciones realizadas sobre 10 muestras de test

# 📊 4. Evaluación del Rendimiento

Evaluamos qué tan bien predice el modelo usando varias métricas de error.

## Métricas de Evaluación

- **MAE** (Mean Absolute Error): Error promedio en valor absoluto
- **RMSE** (Root Mean Squared Error): Penaliza más los errores grandes
- **R²** (Coeficiente de Determinación): % de varianza explicada (0-1)

In [5]:
# Calcular métricas de evaluación
mae = mean_absolute_error(y_test, y_predictions)
mse = mean_squared_error(y_test, y_predictions)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_predictions)

print("📊 Rendimiento del Modelo (sobre datos de Test):\n")
print(f"  🔹 MAE:  ${mae:,.2f}")
print(f"  🔹 RMSE: ${rmse:,.2f}")
print(f"  🔹 R²:   {r2:.4f} ({r2*100:.2f}%)\n")

print("💡 Interpretación:")
print(f"  • En promedio, el modelo se equivoca por ${mae:,.2f}")
print(f"  • El modelo explica el {r2*100:.1f}% de la varianza en Profit")
print(f"  • RMSE de ${rmse:,.2f} indica el error típico de las predicciones\n")

# Mostrar algunas predicciones vs valores reales
print("🔍 Comparación de algunas predicciones:\n")
comparison_df = pd.DataFrame({
    'Valor Real': y_test.values[:5],
    'Predicción': y_predictions[:5],
    'Error': y_test.values[:5] - y_predictions[:5],
    'Error %': ((y_test.values[:5] - y_predictions[:5]) / y_test.values[:5] * 100)
})
display(comparison_df)

📊 Rendimiento del Modelo (sobre datos de Test):

  🔹 MAE:  $6,979.15
  🔹 RMSE: $8,995.91
  🔹 R²:   0.9001 (90.01%)

💡 Interpretación:
  • En promedio, el modelo se equivoca por $6,979.15
  • El modelo explica el 90.0% de la varianza en Profit
  • RMSE de $8,995.91 indica el error típico de las predicciones

🔍 Comparación de algunas predicciones:

   Valor Real     Predicción         Error    Error %
0   134307.35  126703.027165   7604.322835   5.661881
1    81005.76   84894.750816  -3888.990816  -4.800882
2    99937.59   98893.418160   1044.171840   1.044824
3    64926.08   46501.708150  18424.371850  28.377459
4   125370.37  129128.397344  -3758.027344  -2.997540

# 🔍 5. Selección de Features

Experimentamos entrenando modelos con **subconjuntos de variables** para comparar rendimiento.

## ¿Más variables = Mejor modelo?

No necesariamente. A veces:
- Algunas variables tienen poco poder predictivo
- Menos variables = modelo más simple y generalizable
- Evitamos multicolinealidad (variables correlacionadas)

**Experimento**: Entrenar un modelo usando solo **2 de las 3 variables** disponibles.

In [6]:
# Experimento: Modelo con solo 2 features (Administration y Marketing Spend)
# Omitimos R&D Spend para ver cómo afecta al rendimiento

print("🧪 Experimento: Entrenar modelo con solo 2 features\n")
print("   Omitimos: R&D Spend")
print("   Usamos: Administration y Marketing Spend\n")

# Seleccionar solo 2 features
features_reducidas = ["Administration", "Marketing Spend"]
x_train_new = x_train[features_reducidas]
x_test_new = x_test[features_reducidas]

print(f"📊 Dimensiones de datos reducidos:")
print(f"  🔹 Train: {x_train_new.shape}")
print(f"  🔹 Test: {x_test_new.shape}")

# Entrenar nuevo modelo
lin_reg_new = LinearRegression()
lin_reg_new.fit(x_train_new, y_train)

print(f"\n✅ Modelo reducido entrenado")

# Hacer predicciones
y_predictions_new = lin_reg_new.predict(x_test_new)

# Evaluar nuevo modelo
mae_new = mean_absolute_error(y_test, y_predictions_new)
mse_new = mean_squared_error(y_test, y_predictions_new)
rmse_new = np.sqrt(mse_new)
r2_new = r2_score(y_test, y_predictions_new)

print(f"\n📊 Rendimiento del Modelo Reducido (2 features):\n")
print(f"  🔹 MAE:  ${mae_new:,.2f}")
print(f"  🔹 RMSE: ${rmse_new:,.2f}")
print(f"  🔹 R²:   {r2_new:.4f} ({r2_new*100:.2f}%)\n")

# Comparar con el modelo completo
print("🔎 Comparación: Modelo Completo vs Reducido\n")
comparison = pd.DataFrame({
    'Métrica': ['MAE', 'RMSE', 'R²'],
    'Modelo Completo (3 features)': [f"${mae:,.2f}", f"${rmse:,.2f}", f"{r2:.4f}"],
    'Modelo Reducido (2 features)': [f"${mae_new:,.2f}", f"${rmse_new:,.2f}", f"{r2_new:.4f}"]
})
display(comparison)

print(f"\n💡 Conclusión:")
if r2_new < r2:
    perdida = (r2 - r2_new) * 100
    print(f"  • El modelo reducido pierde {perdida:.1f} puntos porcentuales de R²")
    print(f"  • Esto sugiere que R&D Spend es importante para predecir Profit")
else:
    print(f"  • El modelo reducido mantiene buen rendimiento")
    print(f"  • Quizás R&D Spend no aporta mucha información adicional")

🧪 Experimento: Entrenar modelo con solo 2 features

   Omitimos: R&D Spend
   Usamos: Administration y Marketing Spend

📊 Dimensiones de datos reducidos:
  🔹 Train: (40, 2)
  🔹 Test: (10, 2)

✅ Modelo reducido entrenado

📊 Rendimiento del Modelo Reducido (2 features):

  🔹 MAE:  $20,748.95
  🔹 RMSE: $27,199.56
  🔹 R²:   0.0864 (8.64%)

🔎 Comparación: Modelo Completo vs Reducido

  Métrica Modelo Completo (3 features) Modelo Reducido (2 features)
0     MAE                    $6,979.15                   $20,748.95
1    RMSE                    $8,995.91                   $27,199.56
2      R²                       0.9001                       0.0864

💡 Conclusión:
  • El modelo reducido pierde 81.4 puntos porcentuales de R²
  • Esto sugiere que R&D Spend es importante para predecir Profit

In [7]:
# Calcular error en datos de entrenamiento
y_predictions_train = lin_reg.predict(x_train)

mae_train = mean_absolute_error(y_train, y_predictions_train)
mse_train = mean_squared_error(y_train, y_predictions_train)
rmse_train = np.sqrt(mse_train)
r2_train = r2_score(y_train, y_predictions_train)

print("📊 Comparación de Rendimiento: Train vs Test\n")

# Crear tabla comparativa
overfitting_comparison = pd.DataFrame({
    'Métrica': ['MAE', 'RMSE', 'R²'],
    'Train (visto)': [f"${mae_train:,.2f}", f"${rmse_train:,.2f}", f"{r2_train:.4f}"],
    'Test (no visto)': [f"${mae:,.2f}", f"${rmse:,.2f}", f"{r2:.4f}"]
})
display(overfitting_comparison)

# Análisis de overfitting
print(f"\n🔍 Análisis de Overfitting:")
print(f"\n  🔹 RMSE Train:  ${rmse_train:,.2f}")
print(f"  🔹 RMSE Test:   ${rmse:,.2f}")
print(f"  🔹 Diferencia:  ${abs(rmse - rmse_train):,.2f}\n")

# Criterio: si el error de train es < 95% del error de test
umbral = 0.95
if rmse_train < rmse * umbral:
    diferencia_porcentual = ((rmse - rmse_train) / rmse) * 100
    print(f"⚠️ POSIBLE OVERFITTING DETECTADO")
    print(f"   El modelo funciona {diferencia_porcentual:.1f}% mejor en train que en test")
    print(f"\n💡 Esto podría indicar:")
    print(f"   • El modelo memorizó patrones específicos del conjunto de train")
    print(f"   • Podría no generalizar bien a datos futuros")
    print(f"\n🔧 Soluciones:")
    print(f"   • Usar regularización (Ridge, Lasso)")
    print(f"   • Recopilar más datos de entrenamiento")
    print(f"   • Reducir complejidad del modelo")
else:
    print(f"✅ NO SE DETECTA OVERFITTING SIGNIFICATIVO")
    print(f"   El modelo tiene rendimiento similar en train y test")
    print(f"\n💡 Esto indica:")
    print(f"   • Buena capacidad de generalización")
    print(f"   • El modelo no está memorizando los datos")
    print(f"   • Las predicciones son confiables para datos nuevos")

# Comparación de R² para visualizar mejor
print(f"\n📈 Comparación de R²:")
print(f"  🔹 Train: {r2_train:.4f} ({r2_train*100:.2f}%)")
print(f"  🔹 Test:  {r2:.4f} ({r2*100:.2f}%)")
diferencia_r2 = abs(r2_train - r2) * 100
print(f"  🔹 Diferencia: {diferencia_r2:.2f} puntos porcentuales")

if diferencia_r2 < 5:
    print(f"\n✅ Excelente: Diferencia < 5% indica modelo bien ajustado")

📊 Comparación de Rendimiento: Train vs Test

  Métrica Train (visto) Test (no visto)
0     MAE     $6,597.24       $6,979.15
1    RMSE     $8,938.01       $8,995.91
2      R²        0.9536          0.9001

🔍 Análisis de Overfitting:

  🔹 RMSE Train:  $8,938.01
  🔹 RMSE Test:   $8,995.91
  🔹 Diferencia:  $57.89

✅ NO SE DETECTA OVERFITTING SIGNIFICATIVO
   El modelo tiene rendimiento similar en train y test

💡 Esto indica:
   • Buena capacidad de generalización
   • El modelo no está memorizando los datos
   • Las predicciones son confiables para datos nuevos

📈 Comparación de R²:
  🔹 Train: 0.9536 (95.36%)
  🔹 Test:  0.9001 (90.01%)
  🔹 Diferencia: 5.35 puntos porcentuales

# ⚠️ 6. Detección de Overfitting

El **overfitting** (sobreajuste) ocurre cuando el modelo aprende demasiado bien los datos de entrenamiento, pero no generaliza bien a datos nuevos.

## ¿Cómo detectar overfitting?

Comparamos el error del modelo en:
- **Train**: Datos que el modelo vio durante el entrenamiento
- **Test**: Datos que el modelo NO vio

**Señal de overfitting**: Error mucho menor en train que en test

## Criterio de detección

Si el error en train es significativamente menor (por ejemplo, <95% del error de test), podría haber overfitting.

# 🎓 Conclusiones

## 📚 Resumen

En este notebook has aprendido:

### 🔹 Conceptos Fundamentales
- **Regresión Lineal Múltiple**: Extensión de regresión simple a múltiples predictores
- **Ecuación**: $y = b_0 + b_1x_1 + b_2x_2 + ... + b_nx_n$
- **Objetivo**: Minimizar el error cuadrático con múltiples variables

### 🔹 Proceso de Machine Learning Completo
1. **Carga de datos**: Dataset 50 Startups con 4 variables predictoras
2. **Preparación**: Eliminación de variables categóricas, división train/test (80/20)
3. **Entrenamiento**: Uso de LinearRegression de scikit-learn
4. **Evaluación**: Métricas MAE, RMSE y R²
5. **Experimentación**: Modelos con diferentes subconjuntos de features
6. **Diagnóstico**: Detección de overfitting comparando train vs test

### 🔹 Resultados Clave
- Modelo con **3 features** (R&D, Admin, Marketing) logró buen R²
- Interpretación de **coeficientes** permite entender contribución de cada variable
- **R&D Spend** probablemente es la variable más importante
- **No se detectó overfitting** significativo - modelo generaliza bien

### 🔹 Diferencias vs Regresión Simple
| Aspecto | Simple | Múltiple |
|---------|--------|----------|
| Predictores | 1 | Múltiples |
| Poder predictivo | Limitado | Mayor |
| Interpretación | Muy fácil | Requiere análisis |
| Overfitting | Menor riesgo | Mayor riesgo |

### 🔹 Lecciones Aprendidas
- ✅ Más variables **pueden** mejorar predicciones
- ✅ No todas las variables aportan igual valor
- ✅ Importante comparar modelos con diferentes features
- ✅ Siempre verificar overfitting (train vs test)
- ✅ Coeficientes muestran importancia relativa de variables

---

## 🚀 Próximos pasos

### Profundizar en Regresión Lineal

**📖 Recursos recomendados:**

1. **Documentación oficial de scikit-learn**:
   - [LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)
   - [Guía de modelos lineales](https://scikit-learn.org/stable/modules/linear_model.html)

2. **Tutoriales interactivos**:
   - [Real Python - Linear Regression](https://realpython.com/linear-regression-in-python/)
   - [Machine Learning Mastery - Multiple Regression](https://machinelearningmastery.com/implement-linear-regression-stochastic-gradient-descent-scratch-python/)

3. **Teoría matemática**:
   - [StatQuest - Multiple Regression](https://www.youtube.com/watch?v=zITIFTsivN8) (YouTube)
   - [Khan Academy - Multiple Regression](https://www.khanacademy.org/math/statistics-probability/describing-relationships-quantitative-data)

### Temas Avanzados

**🔧 Técnicas de mejora:**
- **Regularización**: Ridge, Lasso, ElasticNet
- **Selección de features**: RFE, SelectKBest
- **Validación cruzada**: K-fold para mejor evaluación
- **Transformación de features**: Polinómicas, interacciones

**📊 Otros modelos de regresión:**
- Regresión Polinómica
- Support Vector Regression (SVR)
- Random Forest Regressor
- Gradient Boosting (XGBoost, LightGBM)
- Redes Neuronales para regresión

**🔍 Diagnóstico avanzado:**
- Análisis de residuos
- Test de multicolinealidad (VIF)
- Detección de outliers influyentes
- Validación de supuestos (normalidad, homocedasticidad)

### Ejercicios Propuestos

**💪 Práctica adicional:**
1. Probar el modelo con cada feature individual - ¿cuál es la más importante?
2. Agregar de vuelta la variable categórica 'State' usando One-Hot Encoding
3. Buscar el subconjunto óptimo de features usando RFE
4. Implementar validación cruzada con K-Fold
5. Aplicar regularización Ridge/Lasso y comparar resultados
6. Visualizar las predicciones vs valores reales en gráficos
7. Analizar residuos para verificar supuestos del modelo

### Datasets Relacionados

**🗂️ Para seguir practicando:**
- [California Housing Prices](https://www.kaggle.com/datasets/camnugent/california-housing-prices)
- [Boston Housing](https://www.kaggle.com/c/boston-housing)
- [Automobile Price Prediction](https://www.kaggle.com/datasets/hellbuoy/car-price-prediction)
- [Medical Cost Personal](https://www.kaggle.com/datasets/mirichoi0218/insurance)

---

**🎯 Has completado exitosamente tu introducción a Regresión Lineal Múltiple!**

**💡 Recuerda:** La clave del éxito en Machine Learning es:
- **Experimentar** con diferentes configuraciones
- **Entender** el comportamiento del modelo
- **Validar** siempre con datos no vistos
- **Iterar** continuamente para mejorar